### ISSUE TITLE
map generation error since bullseye upgrade

### ISSUE THREAD

**Issue by lordfolken** [XCSoar/mapgen#31]
In some cases this seems to happen:

 24 Generating map file for job uuid=7cc6d46e-4537-11ec-b987-525400c7f7bf, name=CentAus, mail=
 25 Setting map boundaries: left=133.0725860595703, right=134.66835021972656, top=-23.259148823094606, bottom=-24.113051732520603
 26 Adding topology...
 27 Creating topology layer city_area ...
 28 Reading dataset vmap0/sas ...
 29 Reading dataset vmap0/soa ...
 30 Generating index file for layer city_area ...
 31 Creating topology layer water_area ...
 32 Reading dataset vmap0/sas ...
 33 Error: Command '['ogr2ogr', '-select', 'nam', '-where', 'hyc=8', '-spat', '133.0725860595703', '-24.113051732520603', '134.66835021972656', '-23.259148823094606', '/opt/mapgen/jobs/7cc6d46e-4537-11ec-b987-525400c7f7bf.working/tmp', '/opt/mapgen/data/vmap0/sas', 'hydro-inland-water-a', '-nln', 'water_a    rea']' returned non-zero exit status 1.
 34 Traceback (most recent call last):
 35   File "/opt/mapgen/lib/xcsoar/mapgen/server/worker.py", line 57, in __do_job
 36     generator.add_topology(compressed = description.compressed, level_of_detail = description.level_of_detail)
 37   File "/opt/mapgen/lib/xcsoar/mapgen/generator.py", line 117, in add_topology
 38     self.__files.extend(shapefiles.create(bounds, self.__downloader, self.__dir_temp, compressed, level_of_detail))
 39   File "/opt/mapgen/lib/xcsoar/mapgen/topology/shapefiles.py", line 97, in create
 40     __create_layer(bounds, layer, datasets[layer['dataset']], downloader, dir_temp, files, index, compressed)
 41   File "/opt/mapgen/lib/xcsoar/mapgen/topology/shapefiles.py", line 59, in __create_layer
 42     __create_layer_from_dataset(bounds, layer, datasets[i],
 43   File "/opt/mapgen/lib/xcsoar/mapgen/topology/shapefiles.py", line 48, in __create_layer_from_dataset
 44     subprocess.check_call(arg)
 45   File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
 46     raise CalledProcessError(retcode, cmd)

**Comment by lordfolken** [comment]
map name: CentAus
generator: XCSoar Map Generator
creation time: 14.11.2021 11:43:07 (1636886587)
latitude range: -24.00158252528044 to -23.07748136025593
longitude range: 133.0210876464844 to 134.18289184570315
author:

**Comment by lordfolken** [comment]
fixed in ce747b5292c3172b180a4073004ebe384d1e00d4
